# Generated by Django 5.0.7 on 2024-09-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
