# Generated by Django 5.0.7 on 2024-09-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_category_options_category_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='task',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
