# Generated by Django 5.0.7 on 2024-09-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
    ]
